### ISSUE TITLE
[Feature Request]..question.

### ISSUE THREAD

**Issue by vladtoa** [bmx666/android-appcachecleaner#140]
is it possible to skip the search for "disabled" apps, from the search algorithm. not just filtering search results, but completely bypassing the search of such apps. 

also, filtering apps with less than 25 kb cache size limit. it would be nice not to type it every time.

thanks in advance!

**Comment by bmx666** [comment]
Hi @vladtoa,

> is it possible to skip the search for "disabled" apps, from the search algorithm. not just filtering search results, but completely bypassing the search of such apps.

Android returns the list of all apps (package name + basic information) almost immediately, but if you set an option "Hide disabled apps" in Settings, then algorithm skips request cache size and icon of that app.

> filtering apps with less than 25 kb cache size limit. it would be nice not to type it every time.

You can set default minimal cache size in Mb only in Settings.

**Comment by vladtoa** [comment]
> but if you set an option "Hide disabled apps" in Settings, then algorithm skips request cache size and icon of these apps by checking basic  information, they also will be excluded from a filter list.

I ask because, it seems there is no difference, "Hide disabled apps" is on or off, the search algo pusses through a fixed number of "241" (in my case) apps, every time.

> You can set default minimal cache size in Mb only in Settings.

I know, that's why I ask for such possibility, as a feature request.

**Comment by bmx666** [comment]
Hi @vladtoa,

> I ask because, it seems there is no difference, "Hide disabled apps" is on or off, the search algo pusses through a fixed number of "241" (in my case) apps, every time.

Android returns list of 241 apps. And algorithm checks every app if it's disabled or not. If app is disabled then it moves to the next app.

> I know, that's why I ask for such possibility, as a feature request.

I was thinking about it, but most people use Mb, anyway I didn't see any reason to clean cache every day, maybe once at week, because after full cleaning process you must reboot your device, otherwise system apps will be unstable. So it will restore all cache back and in the most case it's just a temporary files that displays as 1Mb or less, and if you clean cache then app could skip clean cached files, because they are protected and in use, or app restore back cashed files after receiving a command.
For example, Instagram has always 200Mb reserved cache. And doesn't matter what are you doing that cache will never be deleted. So you can clean all apps, reboot you phone and repeat the same on the next week.

**Comment by vladtoa** [comment]
ok, got it. anyway, with reboot or without, i see a long list of system apps with 0 kb cache.

**Comment by bmx666** [comment]
Hi @vladtoa ,

Please read - https://github.com/bmx666/android-appcachecleaner/issues/87#issuecomment-1440296542 and https://github.com/bmx666/android-appcachecleaner/issues/25#issuecomment-1356230598

If you just want to hide apps that have 0 cache size then it could hide also some apps that have cache size >0 but due to some reason Android returns "null" (undefined value) instead of real value. So you need extra step to process it hide or show? Maybe app could request cache size again, but what if it's still "null"? How much tries? Maybe app right after your request created a file with 10Mb size, but information presented to you it's not valid anymore, but if you have slow smartphone and it could take significant amount of time to recalculate 0 or not apps. So I decided keep algorithm as simple as possible.
