### ISSUE TITLE
[feature request] Force stop

### ISSUE THREAD

**Issue by Pantyhose-X** [bmx666/android-appcachecleaner#167]
Support Force stop user app
## Force stop

<img alt="Screenshot_20240317-105652" src="https://raw.githubusercontent.com/bmx666/android-appcachecleaner/main/fastlane/metadata/android/en-US/images/phoneScreenshots/cache_cleaning_process.png" width=180 />

Some apps may be associated with waking up other apps in the background, which is useful.

**Comment by Lucky390163** [comment]
I also need this

**Comment by Zig-Rust-Odin** [comment]
Force stopping apps that the user is running is very useful, maybe a whitelist is needed to avoid stopping apps.
Force stop waking and background apps. Reduce consumption.

**Comment by TPS** [comment]
[SuperFreezZ)](https://f-droid.org/packages/superfreeze.tool.android/) or [Greenify](https://play.google.com/store/apps/details?id=com.oasisfeng.greenify) do this standalone, but it'd be amazing to have 1 app that can do both _or_ either.

**Comment by bmx666** [comment]
Force stop will be in the next release v2.0.2

**Comment by TPS** [comment]
@bmx666 This just landed on F-droid, & glitches just a little bit:  some apps won't stay closed, but auto-re-activate d/t system or whatever, _& that's ok._  That's not a fail for your app, but something we users might need to adjust elseplace.

I  propose to change from the current force-close ∞× behavior to force-close 1× (to keep app from undefined behavior), clean cache/data (depending on _that_ setting), & then go back to force-close 1× (because some apps like Chromium-based browsers, clean cache will re-activate app), & then move on to next app.

**Comment by bmx666** [comment]
Hey @TPS 

Unfortunately, during my testing I found that some apps, especially from Google, don't stop at all, and it doesn't matter how many times you force stop them. Also don't forget about pending jobs, Android doesn't clean the cache in real time like you expect, it has a background job that triggers the cache cleanup and on some phones it can take 5-30 seconds.

**Comment by TPS** [comment]
> Unfortunately, during my testing I found that some apps, especially from Google, don't stop at all, and it doesn't matter how many times you force stop them.

On such apps, we get ∞ loop of continuous force-stop, & app never progresses.  My proposal is to mitigate that.

**Comment by bmx666** [comment]
I didn't get it. Could you please grab logs with debug version of this behavior?
Main algorithm: If force stop button was found it reset tries, and press button and then wait dialog with OK button, after it sets tries to 0, otherwise if force stop button disabled, decrease tries. By default it's 2 tries.

**Comment by TPS** [comment]
@bmx666 I just tried it.  It looks like on, e.g., Nova Launcher, it tried 6-8× before going on to cleaning.  How do I enable debug mode?

**Comment by TPS** [comment]
![appcachecleaner-log.txt.zip](https://github.com/user-attachments/files/16842900/appcachecleaner-log.txt.zip)

@bmx666 Here you go.  This is setting up the app the way I like & w/ only Nova Launcher being targeted.  This time, there were "just" 4 attempts @ force-stop.

**Comment by bmx666** [comment]
Hey @TPS 

There is no Title in Force Stop Dialog and it detects only Dialog with "Force stop text BLA BLA..." and buttons "Force stop" and "Cancel"

I made dialog checks otherwise it will be a mess because it's hard to determine "Force Stop" button in AppInfo or "Force Stop" button from Force stop dialog. There is no difference. But I will try to change behavior and find "Cancel" button with "Force Stop" button in, at least it will be close to dialog window. I hope no one has Settings AppInfo with "Force Stop" Button and "Cancel" button 😭

**Comment by bmx666** [comment]
I made a new issue #271

**Comment by Lucky390163** [comment]
Ao use app mgr pro app it includes function you want by using accessibility.
![Screenshot_20240903_191639_AppMgr Pro III](https://github.com/user-attachments/assets/4044be6e-1f1d-422b-95f6-d78a53ed29c5)

**Comment by bmx666** [comment]
> Ao use app mgr pro app it includes function you want by using accessibility.

I kindly ask that you refrain from comparing my app with commercial, profit-driven applications. I'm not a professional Android developer; I create apps as a hobby in my spare time. I don't have financial backing to develop and optimize my apps for a wide range of devices.

**Comment by Lucky390163** [comment]
There is no play store link.I can't find it anymore

**Comment by bmx666** [comment]
> There is no play store link.I can't find it anymore

Hi @Lucky390163 , check #101

**Comment by TPS** [comment]
> Please can you provide in the the description clearly.A play store logo.

@Lucky390163 _Did_ you _read_ https://github.com/bmx666/android-appcachecleaner/issues/101 as you were asked?
