### ISSUE TITLE
Pixel 7 

### ISSUE THREAD

**Issue by xmm076** [bmx666/android-appcachecleaner#169]
Hello, pixel 7, 397 applications, android 14, always crashes on application 74-75 when cleaning, no root, everything was fine on android 13

**Comment by bmx666** [comment]
Hi @xmm076, yes, it's because cleaning the cache of some system applications on Android 14 breaks the Accessibility Service. It stops responding, but this is not the Cache Cleaner's fault. I asked people to identify the specific system apps that cause undefined behavior, but I haven't received feedback from anyone. How am I supposed to fix it then?
If you could share this information, or even install the debug version and share traced log, I would be very appreciative.
I have only Android 14 emulator and I couldn't reproduce this issue. Someone also mention that in #149.
I will reopen that issue, mark that as duplicate and close.

**Comment by xmm076** [comment]
Приветствую ,да не могу понять на каких приложениях вылетает,абсолютно на
рандомных даже на установленых

ср, 20 дек. 2023 г., 10:51 Maksim Paimushkin ***@***.***>:

**Comment by bmx666** [comment]
@xmm076 as I mentioned before, please visit #149. Install debug version and share debug log in issue #149. Please stop reply or text something here.

**Comment by bmx666** [comment]
Hi @xmm076 please check a new version v1.10.0 - if some app interrupts cleaning process you will see a dialog that suggests to add the app into the list of ignored apps.

**Comment by bmx666** [comment]
Hi @xmm076, Google recently updated Android 14 and I finally found the root cause.
Google implemented a bug that triggers a recheck of battery optimization in the background job each time the Settings show AppInfo, regardless of whether AppInfo was opened manually by user or by an app. So, if you open too many AppInfo instances, something breaks in the Android System, causing undefined behavior.

```
Sending non-protected broadcast com.android.settings.battery.action.PERIODIC_JOB_RECHECK
```
