### ISSUE TITLE
No free cache

### ISSUE THREAD

**Issue by carlosnewmusic** [bmx666/android-appcachecleaner#18]
In Android 12, when executing the process and modifying the parameters since for me it is: "Uso de almacenamiento" and "Borrar caché" It pretends that you are doing the process but it does nothing more than jump from app to app without freeing the cache

**Comment by bmx666** [comment]
Hi @carlosnewmusic 
- do you have customized Android UI (not standard AOSP settings app)?
- Can you share screenshots of AppInfo and Storage menu (where buttons Clear Data and Clear Cache)?
- Do you try to change language on English? Is it work? Because Android has issue with uppercase and lowercase of non-standard Latin chars like é and some UI are capitalize caption "Clear Cache" into "CLEAR CACHE"

I had a debug version to dump list of accessibility tree, but I need to update it...
Can you try old debug apk and grub logs? -> https://github.com/bmx666/android-appcachecleaner/issues/6#issuecomment-1172952421

**Comment by bmx666** [comment]
Hi @carlosnewmusic I updated debug version. When cache clean will be finished or interrupted you can save log into file and attach it here (no sensitive information, only view tree with button and menu titles).
NOTE: Just check 1-2 apps for dump logs, otherwise log file will be huge.

Rename file extension from ZIP into APK. Remove Release App from phone and install debug version
[app-debug.zip](https://github.com/bmx666/android-appcachecleaner/files/9944808/app-debug.zip)

**Comment by carlosnewmusic** [comment]
> 
* is ColorOs 13 based on Android 13
* 
![imagen](https://user-images.githubusercontent.com/19379457/201548216-15e50ace-a7f4-40f5-9769-1711205e5235.png)
![imagen](https://user-images.githubusercontent.com/19379457/201548224-a4565e4e-6276-4cbb-9ba5-ca7284db84ea.png)
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/9998365/appcachecleaner-log.txt)
* ok I'll try and put you the same as the previous time.
* 
![imagen](https://user-images.githubusercontent.com/19379457/201548376-42579374-ae0d-4be9-a763-39743b68de64.png)
![imagen](https://user-images.githubusercontent.com/19379457/201548380-b8339b29-60b6-48be-aeb1-3e52d1891c8c.png)
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/9998370/appcachecleaner-log.1.txt)

**Comment by bmx666** [comment]
Hi @carlosnewmusic , from your last log and screenshot - you should set search string "Storage usage" in English locale and repeat process to grab log.

From first log, text should be "Borrar caché" - 
D: >>>>>>>>>>>>>>>> android.widget.Button:Borrar caché:com.android.settings:id/button

**Comment by carlosnewmusic** [comment]
> Hi @carlosnewmusic , from your last log and screenshot - you should set search string "Storage usage" in English locale and repeat process to grab log.
> 
[appcachecleaner-log (1).txt](https://github.com/bmx666/android-appcachecleaner/files/10006948/appcachecleaner-log.1.txt)

> From first log, text should be "Borrar caché" - D: >>>>>>>>>>>>>>>> android.widget.Button:Borrar caché:com.android.settings:id/button
[appcachecleaner-log (2).txt](https://github.com/bmx666/android-appcachecleaner/files/10006929/appcachecleaner-log.2.txt)

**Comment by bmx666** [comment]
Hi @carlosnewmusic from first log - something happened with Android accessibility service, and log contain 2 copy of app services. I faced with this issue before and I have no idea why Android do that, but only reboot of smartphone helps. Anyway, English locale works and app can find button.
For Spanish locale you should use "Uso de almacenamiento" and "Borrar caché", please reboot device and grab log, because something goes wrong with Android Accessibility service.

**Comment by bmx666** [comment]
Hi @carlosnewmusic
If you still have a problem, I will reopen this issue again.

**Comment by carlosnewmusic** [comment]
> Hi @carlosnewmusic If you still have a problem, I will reopen this issue again.

works with the latest version by changing the first field to "Uso del almacenamiento"
