### ISSUE TITLE
Material you 3 Design update

### ISSUE THREAD

**Issue by OmarNazzal150** [bmx666/android-appcachecleaner#202]
Hi. I love your app, but there's a problem with the ui/ux. The ui/ux is outdated and has an old material 2 design, and I hate it. So can you pls update Material 3 for a newer ui just like other apps? Thank you.

**Comment by bmx666** [comment]
Hi @OmarNazzal150 , work in progress already - https://github.com/bmx666/android-appcachecleaner/issues/168
But I'm waiting until Google implements a nice way for Settings, currently it's a nightmare because all settings you must create manually and set hooks on each settings to save/get via ViewModel. Too much effort for nothing... I'm just waiting.

**Comment by OmarNazzal150** [comment]
Ok

**Comment by bmx666** [comment]
Hi @OmarNazzal150 

Migration on Material 3 is ongoing, but a lot of UX/UI elements are missing. It's really annoying to re-invent wheel and create buttons, dialogs from scratch...

**Comment by bmx666** [comment]
Hi @OmarNazzal150 , migration was done. Check the new release v2.0.1  🎉
