### ISSUE TITLE
[Feature Request] Cleaning a little bit more?

### ISSUE THREAD

**Issue by malespiaut** [bmx666/android-appcachecleaner#207]
Hello,

I love you application, and I use it regularly since I've discovered it.

I was using LTE Cleaner (https://github.com/TheRedSpy15/LTECleanerFOSS) before that, and I thought about replacing LTE Cleaner with Cache Cleaner.

However, it has come to my attention that LTE Cleaner cleans things that Cache Cleaner doesn't touch. As a matter of fact, I've cleaned 3 Gb of junk with LTE Cleaner, right after the end of the execution of Cache Cleaner.

My request therefore is: Can Cache Cleaner cleans as much as LTE Cleaner? Or is the feature going out of the scope of your project?

Best regards, and thank you very much for your effort.

**Comment by bmx666** [comment]
Hi @malespiaut

> Can Cache Cleaner cleans as much as LTE Cleaner? 
No

> Or is the feature going out of the scope of your project?
Yes, Cache Cleaner only focuses on using the Accessibility Service to find Clear Cache buttons and do perform click on them without any additional logic

People asked about features that hard to fit into Google Policy.
I spent months getting Google's approval to publish my app and got 2 strikes, Google suspended my app twice, I appealed it twice during 6 months and finally got banned from publishing Cache Cleaner because people can't read the information that Cache Cleaner doesn't work on every phone in the world due to my resource limitations, that's all  I made stupid checkboxes about Google Policy and expanded the description to avoid getting my new account banned and Cache Cleaner suspension again. Now users who send complaint about Cache Cleaner as virus or misleading ignored by Google Team.
The second problem is that independent developers like me are completely ignored by Google in case of mistakes and misunderstandings, so only large companies have the opportunity to publish whatever they want, even partially consistent with Google's policies. I don’t have the time and resources to fight and prove something to Google, I added a Help menu, an introduction on the first screen, but some people simply ignore all the information and want to get a fully working application for free and without advertising, while expressing angry comments containing obscene vocabulary, and I also receive notifications from Google about complaints from users who simply cannot read. I did everything I could, and I don’t want to expand the functionality of the application, which will be published on Google Play, in the meantime, the functionality can be easily added for F-Droid.
