### ISSUE TITLE
Closing app revokes Accessibility permission

### ISSUE THREAD

**Issue by puppykickr** [bmx666/android-appcachecleaner#21]
The app works great, but whenever it is closed the Accessibility permission is revoked, causing this permission to need to be granted again each time the app is used.

Also, the Accessibility allows for quick access from an additional button that appears in the navigation bar.
This button is non-functional for this app and unnecessary.

**Comment by bmx666** [comment]
Hi @puppykickr **please read README**

> Press Accessibility button to interrupt process OR wait until process will be finished

> NOTE: Starting with Android 11 it is not possible to dynamically add and hide the accessibility button and the accessibility service must be started with it. After closing AppCacheCleaner, the accessibility service will be automatically destroyed. That is why every run AppCacheCleaner need to re-enable access to Accessibility.

I'm not pro Android Application developer, I made this app for fun because was frustrated ADs, delays and payment and shared with people. You can contribute to this project and if you know how to do it better! 🥳

**Comment by gbdomubpkm** [comment]
Hello @bmx666

In any case, thank you for your work on this very useful app for me, which tends to empty the cache of apps often.. This app has potential for improvement.

Regarding the revoking of the accessibility permission, personally, I find that it provides additional security.

That said, there is probably a solution because this 'problem' does not exist with the Power Menu app (Vishnu NK) or others, but I'm not a developer so I might be wrong.

Personally, I made a shortcut with the Shortcut Maker app (Rushikeh Kamewar) to the Accessibility settings of apps.

**Comment by puppykickr** [comment]
@bmx666 
I was just making sure that I was not the only one that has noticed this thing with the Accessibility.

Perhaps if the closing of the app did not force close the app the Accessibility permission would not be turned off.

I have seen that the permission is not revoked if I back out of the app in another way (using the Home or Recents navigation buttons) rather than using the 'close app' button in the app.

Once again, thank you for this app.
It is a very nice way to save time from clearing caches manually.

**Comment by e-t-l** [comment]
I tried looking through the source code of some other apps that have Accessibility permission (and don't lose it when the app is closed), but I haven't yet identified any obvious differences between how you and they handle permissions. I'm just brainstorming here, but one thing that _might_ prevent the permission from being destroyed is making this app a Device Admin using [the Device Administration API](https://developer.android.com/guide/topics/admin/device-admin). (The downside is that this grants the app unnecessarily broad privileges, and means it can't be deleted without first revoking Device Admin status, which could make some of the more paranoid userbase feel worried.)

**Comment by bmx666** [comment]
@e-t-l yes, before creating this app I tried to use screen overlay, otherwise it's not possible to interrupt clean process, but I didn't find nice examples that works on all platforms since Android 6 up to Android 13. If you have links to sources it will be nice 🙂

**Comment by bmx666** [comment]
@e-t-l  I'm investigating how [Click Assistant](https://play.google.com/store/apps/details?id=com.rise.automatic.autoclicker.clicker) works.

**Comment by RichardBeisser** [comment]
@bmx666
I have also installed the App droidVNC-NG:
https://github.com/bk138/droidVNC-NG

This App also uses the accessibility service of android.
This App can start on boot and it starts without any message and without requiring any permission.
When I look into accessibility permissions, the permissions ist still granted.
Perhaps you can use the same mechanism to keep the permission.

**Comment by bmx666** [comment]
Hi @RichardBeisser thanks, but I had already read about that and trick was using ADB. But it's not an option for regular users, they don't know about adb, and even how to use it.
2nd major reason is Google Play, your app can't be published on market, it can't use Accessibility without asking an user permission and user agreement, that's why I spent 2 months to publish my app on Google Play and I did a lot of preparation to follow Google Policy about "dangerous permissions", and I don't want to deploy 2 separate versions.

Read more about Google Policy:
* https://support.google.com/googleplay/android-developer/answer/10964491?hl=en
* https://support.google.com/googleplay/android-developer/answer/9888170?hl=en
* #50

**Comment by RichardBeisser** [comment]
> 2nd major reason is Google Play, your app can't be published on market, it can't use Accessibility without asking an user permission... and I don't want to deploy 2 separated versions.

Thanks for explaination.
What about following:
publish automatic Accessibility permission granting versions on fdroid, and a version with manual granting on PlayStore

And to avoid further enquery (like my one ;-)  ), explain it in the app description at PlayStore, including that there is a version with automatic granting at fdroid.

Or another suggestion:
post the automatic granting version only here at github if you dont want to have different versions in AppStores.
That is what for TotalCommander-App is done:
--> https://www.ghisler.com/android.htm
--> What's new in Total Commander 3.32 (May 17, 2022):
Removed all functions to install apk files manually by request from Google. Backup of APKs is still possible, but not restore. See our forum for more information.
https://www.ghisler.ch/board/viewtopic.php?t=77349
