### ISSUE TITLE
Display Total Cache Size Before Cleaning

### ISSUE THREAD

**Issue by heberjeur** [bmx666/android-appcachecleaner#214]
I suggest adding a feature to the "Cache Cleaner" app that displays the total size of caches across all applications before initiating the cleaning process.

Including the sum cache sizes would enhance user experience and improve the effectiveness of cache cleaning.

![Screenshot_20240313-224446_Cache Cleaner](https://github.com/bmx666/android-appcachecleaner/assets/11852634/09f76824-0c96-4ced-b7f2-55b9deb97ffa)

**Comment by bmx666** [comment]
Hi @heberjeur ,

Thanks for the idea and I had plans to add it, but I want to add it with description, because many people without background of Android cache expects it will be cleaned 2.5GB, and not 1.5Gb only (because some cache is blocked by running apps or on an external storage)

But please take into account as I replied to you early:

> Android shows sum of two separated cache places - internal private cache (/data/data/com.my.package/cache) and external public cache (on /sdcard/Android/...).
> Android never clears the external public cache, only when you uninstall app. 

Links -> https://github.com/bmx666/android-appcachecleaner/issues/25#issuecomment-1356230598 https://github.com/bmx666/android-appcachecleaner/issues/6#issuecomment-1211641529

So I need to update README and Help menu before.

**Comment by bmx666** [comment]
I added cache size in title just for now
