### ISSUE TITLE
get cache size of apps for the custom list

### ISSUE THREAD

**Issue by Knirps1** [bmx666/android-appcachecleaner#223]
Since version 1.10.8 (earliest version with this bug in fdroid repo, last known working version is 1.10.5), the sum at the end always shows 0KB. Despite me knowing there were over 200 MB cleaned.

It is still the case on 1.11.1 and all versions in between.

This is on Android 10 (Nokia 6.1)
![photo_2024-03-27_17-08-02](https://github.com/bmx666/android-appcachecleaner/assets/52383078/8fbfd5f6-4642-49ef-8f47-05af8a489832)

**Comment by bmx666** [comment]
Hi @Knirps1 

Could you please verify and confirm that cleaned apps don't restore their cache back?
Read my comment here -> https://github.com/bmx666/android-appcachecleaner/issues/214#issuecomment-1997773210

**Comment by Knirps1** [comment]
I just checked with the youtube app and that went from 78.22 MB directly before to 1.63 MB directly after cleaning. It still showed 0KB cleaned.

**Comment by Knirps1** [comment]
I did some testing and it turns out, this only happens with custom lists.

**Comment by bmx666** [comment]
> I did some testing and it turns out, this only happens with custom lists.

Yes, get cache size of apps is expensive IO operation, especially on old phones. The Cache Cleaner set as NULL cache size for all apps and pass list of package names associated with custom list into service and it opens App Info and do cleaning process. After returning back to main screen it checks that cache size is NULL and return 0.

**Comment by bmx666** [comment]
> I can confirm that this is true even after the latest update version 1.11.1, after updating the app via F-Droid (Droid-ify) and testing this just moments ago.
> 
> EDIT: Confirmation of actual data deletion in the system (despite Cache Cleaner showing 0KB deleted) was done by checking full system-wide free-space before, and then again after, the usage of Cache Cleaner. This system-wide free-space test was done via the DiskUsage app (https://f-droid.org/packages/com.google.android.diskusage/).

Please take as note, when you pressing "Clean Cache" button, Android doesn't clean cache immediately, it creates a list of background tasks to clean cache later and update statistic with delay.
That's why you can get 0Kb in total, because Android returns the same statistic for app and background task is not finished yet, or not updated statistics yet. And if Cache Cleaner got from Android it's 200Mb then after cleaning process has been finished it still could be 200Mb reported by Android, but right after Android will update it.

**Comment by Knirps1** [comment]
For me it is consistently every time since version 1.10.8. I downgraded for testing and went up version by version in the fdroid archive repo. Every time I cleared the same custom list and would get the cache from fdroid (the cache cleaner apk) reported as cleaned and with version 1.10.8 it started to report 0KB every time. I used the same list for months and it never showed 0KB and it has only shown 0KB for weeks with at least daily usage.

**Comment by TripleEYE** [comment]
As @Knirps1 mentioned (thanks for testing btw), and also from my personal experience, this used to work just fine (even in lists, as far as I can recall). So ok I understand now why it happens, but it worked before so can't it work again? Otherwise I recommend at the very least putting a pop-up message warning of this together with the list-selection screen.
Though I personally think the cleaned cache being shown is a vital part of the user experience.

**Comment by bmx666** [comment]
Hi @Knirps1, performance update was made since v1.11.0. All slow operations were dropped for the custom list. I could return these logic back, but you can imagine that someone select 200+ apps for the custom list and Cache cleaner starts calculate size of apps around 10s (on modern devices) and up to 1 minute on old smartphones. So there's no good or bad option.

**Comment by Knirps1** [comment]
Where the slow operations dropped with 1.11.0 or before that? What I'm describing happens since before that version. If you don't want to revert the drop of slow operations, it should be possible to test for it and change the message shown. Another possibility that takes more effort is to put it into a setting and let the user decide. I understand if you don't pursue this option.

**Comment by bmx666** [comment]
Hi @Knirps1 , please update on [v1.11.2](https://github.com/bmx666/android-appcachecleaner/releases/tag/v1.11.2)

**Comment by Knirps1** [comment]
It works again and the time it took with a list of 12 apps wasn't really noticeable. Thank you

**Comment by TripleEYE** [comment]
I will wait until the update appears on Droid-ify, but I'm so excited it works again.
Thank you @bmx666! 🙏
