### ISSUE TITLE
[feature request] Additional custom cache clearing programs.

### ISSUE THREAD

**Issue by gbdomubpkm** [bmx666/android-appcachecleaner#24]
Hello.
Currently two cache clearing options. I think it would be useful (for me it would be) to be able to program one or more additional custom cache clearing programs. If possible, allow a label to be entered for each additional program.
Regards

**Comment by Grossdm** [comment]
> Hello. Currently two cache clearing options. I think it would be useful (for me it would be) to be able to program one or more additional custom cache clearing programs. If possible, allow a label to be entered for each additional program. Regards

Do you want to clear cache for a custom list of apps?

**Comment by gbdomubpkm** [comment]
Exact

**Comment by bmx666** [comment]
Hi @gbdomubpkm 

Could you please add more details related to UI/UX behavior?
- for example I can add it into context menu where you can add, remove or edit custom lists
- and if custom list exists, then extra clean cache button will be added on main screen.
- when you press clean button, what are you expecting? Start to clean cache immediately , show checkbox lists or add option for each custom list (skip checkbox and clean immediately or show list)?
- when you find optimal solution for most users I can start to implement prototype.

I want to left main screen as simple as possible, because this feature is not popular and can confuse users. Also it's add unnecessary complexity in UI logic.

**Comment by gbdomubpkm** [comment]
Hi @bmx666
Frankly, I did not think about a possible complexification of the interface. My idea was to stay as close as possible to the functioning of what already exists. Forget if you think it weighs down the interface. It's already a godsend that you made this app.

**Comment by bmx666** [comment]
@gbdomubpkm no problem, I will think about it, how do it better from UI/UX side, because from programming side it's not difficult and pretty easy.

**Comment by e-t-l** [comment]
Thanks for directing me to this issue! I had read through the titles of all the existing issues but hadn't realized this one was the same as the one I was creating. Here is my input regarding the UI design:


> * for example I can add it into context menu where you can add, remove or edit custom lists

That seems like a good place to put it. In fact, I think the context menu should just have an option like "edit custom lists", which launches a Custom Lists activity where lists can be added/edited/deleted. It would be worth putting all the custom lists here because....
> * and if custom list exists, then extra clean cache button will be added on main screen.

....If you'd like to keep the main app screen uncluttered, you might want to have a single button for something like "Clear custom app list"; when tapped, if the user has only 1 custom list, then that one is cleared, while if they have more than 1 custom list saved, then they can select which one to run. Otherwise, adding a button to the main screen for _every_ custom-defined list could get very cluttered very quickly. 
> * when you press clean button, what are you expecting? Start to clean cache immediately , show checkbox lists or add option for each custom list (skip checkbox and clean immediately or show list)?

IMO When the clean button is pressed, it should start cleaning immediately. The checkboxes are unnecessary, since the user has already defined this as the list of apps they want cleaned.

**Comment by bmx666** [comment]
I made a lot of refactoring and some preparations in the develop branch to implement "Custom lists"

**Comment by maverick74** [comment]
Let me just add an "I want this as well!" :)
