### ISSUE TITLE
Logger deactivation

### ISSUE THREAD

**Issue by heberjeur** [bmx666/android-appcachecleaner#26]
Hi @bmx666, As you know, privacy is important nowadays, so can you remove timber from your stable release or, at a minimum, add an option to deactivate permanently this logger?

![Screenshot_20221217-193752_Warden](https://user-images.githubusercontent.com/11852634/208257077-a652c74c-39ac-4196-b63c-60a48d5e1267.jpg)

**Comment by bmx666** [comment]
Hi @heberjeur , nice, could you please recommend an alternative library for my purpose?
App uses Timber to switch between logcat in release build and log file for debug build. I didn't look any further when I found Timber and just integrated it 😜

**Comment by gbdomubpkm** [comment]
What is the nature of the risk if there is one now ? Is there a leak or transmission to an entity of some personal data ?

**Comment by bmx666** [comment]
Hi @heberjeur  I removed Timber in release build, I still don't know where is leak, because they have opensource project... Anyway, next release will be not soon, because it's hard to push updates on F-Droid, it can take few days, weeks or months.

**Comment by gbdomubpkm** [comment]
F-Droid successful build today :

![screenshot20221219_164542739](https://user-images.githubusercontent.com/50362604/208465381-19e26371-dc7a-458c-8ff4-b15bcf4da709.png)
🙂

**Comment by bmx666** [comment]
Hi @heberjeur that's is not leak information. It's just warning for developers to remove sensitive and security information. You can do it with Timber too, by overriding log calls in release. Anyway, it was not necessary, but I did that, because I wanted to reduce dependencies from external libraries and left only necessary, because Timber library was not really required.

**Comment by heberjeur** [comment]
@bmx666 Thanks for your clarifications
