### ISSUE TITLE
Flickering program icons

### ISSUE THREAD

**Issue by mirror176** [bmx666/android-appcachecleaner#279]
This mostly went away after a restart of the program where loading into "ignore apps" list has the icons appear, then flicker away and back once. Before that on first launch I found program icons appear for a short moment (few frames at most) and disappear to the left of names/descriptions. Keeps happening over and over and each icon has its own appear/disappear timings. Started after upgrading from 2.2.0 to 2.2.1 from fdroid. I likely went into "ignored apps" first as I was also disabled stopping keyboard around the same time but may have done that just before updating. I don't recall if I had the program left open or not during the update. Phone=Samsung Galaxy S20 FE 5G UW. (SM-G781V)  with One UI v5.1 and Android v13.

**Comment by mirror176** [comment]
I also observed I was unable to minimize my keyboard when searching for apps to ignore. Pressing the button to minimize the keyboard would have it flicker away and immediately back up. Workarounds were either not using search or enter enough entries that what I needed was not under the keyboard. Haven't yet reproduced it since program restart.

**Comment by bmx666** [comment]
Hi @mirror176 there is no changes in UI between 2.2.0 and 2.2.1, only business logic of force stop algorithm https://github.com/bmx666/android-appcachecleaner/compare/v2.2.0...v2.2.1

Flicking effects is expected because I don't wanna spent time for better UI experience. It just update list automatically without extra coding.

About keyboard, it's not reproducible on AOSP. I don't have any issues on some Nexus, Pixel and Sony Xperia. Please report about it that to Samsung.
