### ISSUE TITLE
Consider moving status/exit icon

### ISSUE THREAD

**Issue by mirror176** [bmx666/android-appcachecleaner#280]
During runs, with the current location it covers the cache + total counter on screen of each program during clearing. Moving most anywhere else (higher, lower, or some to the left) could cover less relevant information to the task at hand. This doesn't impact how the program itself runs and getting cache sizes is faster from the main program screen instead of each of these settings pages it opens. Observed on v2.2.1 with phone=Samsung Galaxy S20 FE 5G UW. (SM-G781V) with One UI v5.1 and Android v13.

**Comment by bmx666** [comment]
For business logic it doesn't matter because Accessible service could read covered UI elements. If you don't like current UI behavior, please feel free to fork project and suggest pull request that could change behavior. Otherwise I don't have time to put any effort to UI improvements because my major goal was always to focus on cleaning algorithm and UI just as option.
