### ISSUE TITLE
App no longer shows amount of space freed up

### ISSUE THREAD

**Issue by steve51184** [bmx666/android-appcachecleaner#285]
After cleaning it always shows 0 kB started happening after 2.2.1 I think 

![Screenshot_20240917-221452](https://github.com/user-attachments/assets/af429a82-54a0-41e4-a979-b7146d8d8ad7)

**Comment by bmx666** [comment]
Please read about it here (and link in comment) - https://github.com/bmx666/android-appcachecleaner/issues/214#issuecomment-1997773210

**Comment by bmx666** [comment]
@steve51184 @nvllz The algorithm for calculating cache size was changed in version 1.11.1 to calculate only the internal cache size and has not changed since then.

https://github.com/bmx666/android-appcachecleaner/commit/dd9008ca9158eb1245538a847c2851ed8eaaea9e

**Comment by bmx666** [comment]
In Android, apps can store temporary data (cache) in two types of cache directories: **internal cache** and **external cache**. Here's a breakdown of the differences between these two:

### 1. **Internal Cache**
   - **Location**: Stored within the app’s private internal storage. This is a specific area reserved for the app within the phone’s storage.
   - **Path**: `/data/data/<app_package_name>/cache`
   - **Accessibility**: 
     - Only the app that created the cache can access it. 
     - Other apps, and even the user without root access, cannot access this cache directly.
   - **Persistence**: 
     - It is automatically cleared when the app is uninstalled.
     - The system can clear the cache if the device is running low on storage, though it’s not guaranteed.
   - **Usage**: Used for storing small and temporary data that the app frequently needs, such as image thumbnails or session data.
   - **Security**: More secure since it is not accessible by other apps or users.
   - **Example**: If a messaging app stores conversation images in the cache, they will remain private to the app and can't be accessed externally.

### 2. **External Cache**
   - **Location**: Stored on the external storage (which may or may not be a physical SD card) but is generally a shared storage area accessible by all apps.
   - **Path**: `/storage/emulated/0/Android/data/<app_package_name>/cache`
   - **Accessibility**:
     - Can be accessed by other apps or the user through a file explorer.
     - Permissions may be needed for certain actions in modern Android versions.
   - **Persistence**: 
     - Like the internal cache, it is cleared when the app is uninstalled.
     - The system can also clear external cache data if it’s running low on space.
   - **Usage**: Used for storing larger, temporary files that don’t need to be private to the app, such as files that might be shared with other apps or accessed by the user.
   - **Security**: Less secure than internal storage because files can be accessed by other apps or users.
   - **Example**: A media app might store downloaded images, videos, or audio files in the external cache, allowing other apps or users to access them.

### Key Differences:
| **Feature**             | **Internal Cache**                              | **External Cache**                              |
|-------------------------|-------------------------------------------------|-------------------------------------------------|
| **Location**            | Private internal storage                        | Shared external storage                         |
| **Access**              | Only the app that created it can access it      | Other apps and users can access it              |
| **Persistence**         | Cleared when app is uninstalled or storage is low | Cleared when app is uninstalled or storage is low |
| **Security**            | More secure (isolated to the app)               | Less secure (can be accessed by other apps/users) |
| **File Size**           | Typically used for smaller cache data           | Can store larger files, suitable for media apps |
| **Use Case**            | Storing temporary internal data, like preferences or session data | Storing media files or other data that can be shared |

Both internal and external caches are used to improve performance and speed up processes by reducing the need for repeated downloads or computations, but they differ in access levels and the types of data stored.

**Comment by bmx666** [comment]
Sorry, but I didn't want implement this feature at all, because people don't understand difference between internal and external cache, locked files by app that could not be cleaned from cache, files that recreates by app again after cleaning and etc. If you open YouTube app as example, surf a little bit and then clean cache, with high probability you will get greater than 0 Kb, the 2nd time if you try clean it again, you will get 0 Kb. For example, apps like Instagram keeps 200Mb cache and can't be cleaned, only force stop remove cache.

If people continue report or blaming that works on many other devices, I will just remove cache calculation. Like headache from my side.

**Comment by bmx666** [comment]
![Screenshot_20240926-101055](https://github.com/user-attachments/assets/2ea58269-aefc-4850-8bb7-69050aa6eb52)

**Comment by bmx666** [comment]
1. Clean cache process is postponed by system. I will do it later... So Cache Cleaner get back the same size of cache.
2. Sometimes Cache Cleaner can't get cache size after the cleaning process - something related to Android system issue, it return "null" instead of usage info, and I decided to return 0 in that case.
3. Some background services of apps automatically restore cache back, so when you press "Clean Cache" button and see 0 bytes, then it will reset back to the same cache size after.
4. Some background services during cleaning process can allocate even more cache, in that case I decided return also 0.

**Comment by bmx666** [comment]
I wouldn't to continue this discussion. Cache cleaner starts calculate cache right after process has been finished, so if you clean 100 apps, you have high chance to see right size for top 50 apps in the list. The latest app could probably return the same size, or NULL, because it doesn't have enough time, when Cache cleaner requests cache size of apps. Also keep in mind, Android keep in cache size of cache each app and return 0 to user as UI-friendly crap. Meanwhile Android creates background task that should really wipe cache.
