### ISSUE TITLE
App opens "App permissions" instead of storage and gets stuck. 

### ISSUE THREAD

**Issue by PRinceBhai** [bmx666/android-appcachecleaner#311]
App opens "App Permissions" instead of "Storage" and gets stuck looking for "cache". This happens 10/10 times on several random apps, ever since the material/monet UI update. This used to only happen 3/10 times before. I've tried reinstalling the apps several times, disabling battery optimization.

Here is a video of the problem (prior to recording it was also getting stuck on Discord):
https://youtube.com/shorts/WWsqRfgdEZI

I've also attached a Screenshot of the settings I currently use, they help a little in this case. (Note that I've tried with Default settings aswell and this problem still occurs).
![Screenshot_20241130-185929042.jpg](https://github.com/user-attachments/assets/0517f895-e6db-45d2-bac1-7199693eb5d6)

Device: Xioami Redmi Note 3
OS: Colt OS 
Version: Android 10

**Comment by bmx666** [comment]
@PRinceBhai  read Help in App or README here on main page about customize settings ui and scenarios.

**Comment by PRinceBhai** [comment]
> @PRinceBhai  read Help in App or README here on main page about customize settings ui and scenarios.

The text entries are already there in the app that are the same as App Settings's "Storage & Cache" and "Clean Cache". Like I said it sometimes works and sometimes it doesn't. Did you watch the video I've linked in the issue?

**Comment by PRinceBhai** [comment]
> Did you read section about scenario for Xiaomi? It was mentioned during first boot, in the help and README. Just set different scenario.

I've read that section, I'm not on MiUi, I'm using a Custom AOSP Rom. Setting the cleaning scenario to "Xiaomi MiUi" makes it not work at all, it doesn't even open the "Storage & Cache" button/label's menu.

Battery optimization for it is also disabled. Like I said this problem has only increased ever since the Monet/Material UI before it used to work better than  it does now.

**Comment by bmx666** [comment]
@PRinceBhai I have no time to support this project anymore, please feel free to add your custom scenario base on Default.
https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/main/java/com/github/bmx666/appcachecleaner/clearcache/scenario/DefaultClearScenario.kt

There are already 10+ custom AOSP ROMs that break the default, and no one wants to implement them because they have no skills in Android development.
Sorry, but I've already spent 500+ hours developing this app and only got a few endorsements and a couple coffees, I'm not interested in continuing to develop it anymore.
