### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by cyber-sec0** [bmx666/android-appcachecleaner#314]
After adding the filter for "1 KB", it doesn't get saved after reopening the app on Android 14.

A minimum of "1 KB" for cache size should be required and default for all apps, currently the app shows "0 KB" cache apps in the list, and attempts to clean all of them, unnecessarily.

After cleaning is done, the app goes back through every single app configuration screen again, so it looks like the screen is flickering "doing the backward inverse process" as if each app setting were being closed, which isn't necessary, and even at the end of this process there's still one configuration screen opened anyway.

There's no refresh current page button, and the app doesn't refresh the list of apps that were just cleaned, so it looks like it didn't work, although it worked.

After going to the app settings and writing "1 KB" as the minimum cache size, it works and gets saved, but then I can't erase it and leave the field blank (this behavior should default to "0 KB" so that the user doesn't have to manually write it).

Even after going to the app settings and setting "1 KB" everytime I open any cleaning list, I still see many "0 KB" apps.

Unselect all button still shows up even when no apps were select, clicking on this button creates a "refresh" flickering screen effect that doesn't do anything. The button should be hidden by default unless 1+ app(s) were selected.

The app cleaning is still slow even after lowering all "timeouts", other apps provide a "turbo" cleaning mode...

**Comment by bmx666** [comment]
```
After adding the filter for "1 KB", it doesn't get saved.
After going to the app settings and writing "1 KB" as the minimum cache size, it works and gets saved, but then I can't erase it and leave the field blank (this behavior should default to "0 KB" so that the user doesn't have to manually write it).
```

No update here, another complex logic. Why do people get upset about this? Do you clear your phone's cache every hour? Just use this app once a week, that's enough.

```
After cleaning is done, the app goes back through every single app configuration screen again, so it looks like the screen is flickering "doing the backward inverse process" as if each app setting were being closed, which isn't necessary, and even at the end of this process there's still one configuration screen opened anyway.
```

Please contact with Google and ask about this crap, it was discussed here many times. I spent several months to find root of cause and implement workaround to make it work on Android 14 and Android 15.

```
There's no refresh current page button, and the app doesn't refresh the list of apps that were just cleaned, so it looks like it didn't work, although it worked.
```

What for? Cache of app could be updated, even in background.

```
Unselect all button still shows up even when no apps were select, clicking on this button creates a "refresh" flickering screen effect that doesn't do anything. The button should be hidden by default unless 1+ app(s) were selected.
```

You skip here a lot of feature from the first steps...You CAN apply filter 50Mb, select all app, then apply filter 100Mb and unselect all apps. BUT apps between 50Mb and 100Mb MUST BE CHECKED. So you have additional level, visible for user now and all apps, complex logic. I did it as simple as possible under the hood, because otherwise it was like .... no thanks.

```
The app cleaning is still slow even after lowering all "timeouts", other apps provide a "turbo" cleaning mode...
```

Oh sorry, that you're using open source free app without any ADs and developed by only one person in free time.

**Comment by cyber-sec0** [comment]
I was only trying to be helpful and let you know of these things. They were only suggestions for improvement/issues, not personal attacks.
If you consider every bug report a personal attack, well I wish you the best...

I was willing to help as I could, but nvm. Removing my repository star.

**Comment by bmx666** [comment]
Sorry, but please practice to leave comments. I didn't notice any polite messages. And the latest one... It was absolutely rude. You can remove star and it didn't change anything. And don't forget to remove my app also.
