### ISSUE TITLE
Granting permissions via ADB

### ISSUE THREAD

**Issue by RichardBeisser** [bmx666/android-appcachecleaner#36]
Hello,

i am using your app on Amazon FireTV-Stick.
FireOS is based on Android.
In FireOS, there is no GUI to manage the 2 neccessary permissions for Android Cache Cleaner

How do I grant the permissions via ADB?

Using ADB over IP is possible on FireOS/FireTV-Stick

I think, is is something like
adb shell cmd appops set XXXXXX YYYYYY allow
and
adb shell settings put secure enabled_accessibility_services XXXXXX/.InputService

Thanks

**Comment by bmx666** [comment]
Hi @RichardBeisser 

I'm not sure if it's possible on some devices. You can check this link and comments
https://gist.github.com/mrk-han/67a98616e43f86f8482c5ee6dd3faabe

PACKAGE_NAME - com.github.bmx666.appcachecleaner
SERVICE_NAME - com.github.bmx666.appcachecleaner.AppCacheCleanerService

Can you also check if [scrcpy](https://scrcpy.org/) - [source](https://github.com/Genymobile/scrcpy) will work?

P.S. In any case, if you find a solution, please leave a comment here. In the meantime, I will close this issue, as it is not related to the application at all.

**Comment by RichardBeisser** [comment]
> If you find a solution, please leave a comment here. In the meantime, I will close this issue, as it is not related to the application at all.

It is possible to grant the permissions via ADB:

`adb shell cmd appops set com.github.bmx666.appcachecleaner allow`

`adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner/com.github.bmx666.appcachecleaner.AppCacheCleanerService`

But your app seems to have a problem with the control of the FireOS-Menu.
It stopps at first App-Entry:
![CC](https://user-images.githubusercontent.com/47367173/209865779-ee7b99ee-18ad-4da9-b14a-0753e578a8b0.png)
![Dialog](https://user-images.githubusercontent.com/47367173/209865783-ed8fa417-091e-41f4-8b70-2dc005ee63f9.png)

> Can you also check if [scrcpy](https://scrcpy.org/) - [source](https://github.com/Genymobile/scrcpy) will work?
This tool seems to work too on FireOS, but I have to find out the equivalent Keystrokes for the keys of the remote control
At the moment, I am using DroidVNC:
https://github.com/bk138/droidVNC-NG

**Comment by bmx666** [comment]
Hi @RichardBeisser 
FireOS UI is not standard at all and it will better to analyze it. Because current app is looking for "Storage" menu -> perform click -> find "clean cache" button -> perform click
Looks like on FireOS these steps should be different and new WORKAROUND is required for it.
Anyway - easiest way to debug and grub full node tree of view.
You can install Android Studio (doesn't matter which platform Linux, Windows or MacOS), download source of app and build debug version. Debug package has suffix ".debug" - **com.github.bmx666.appcachecleaner.debug**
You can check any app (1 is enough) after process will be finished it will generate report in txt-file. This file should contain structure of view nodes which can be helpful for further investigation.

**Comment by RichardBeisser** [comment]
@bmx666
Hello,

did you made some changes to package name / servicename?
With V 1.0 and V 1.0.2, this command via ADB 
`adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner/com.github.bmx666.appcachecleaner.AppCacheCleanerService`
do not work any more.
With V 0.1.5 --> no problems to grant permissions

So I cannot compile a debug-version for Testing.

**Comment by bmx666** [comment]
Hi @RichardBeisser 

Please read my previous comment again 😉

> Debug package has suffix ".debug" - com.github.bmx666.appcachecleaner.debug

**Comment by RichardBeisser** [comment]
@bmx666

I read that about the suffix

I am talking about the the self-compiled debug-version and the normal Version >= 1.0.0 from f-droid

`adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner/com.github.bmx666.appcachecleaner.AppCacheCleanerService`
does not enable the neccessary right for normal version from f-droid

adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner.debug/com.github.bmx666.appcachecleaner.AppCacheCleanerService
does not enable the right for debug version

**Comment by bmx666** [comment]
Hi @RichardBeisser 

You should apply suffix to all package names, because service is located now in debug package!

> adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner.debug/com.github.bmx666.appcachecleaner.debug.AppCacheCleanerService

I also recommend to uninstall all app packages release and debug, then reboot device. Because sometimes Android still handle Accessibility service, even app was removed. Yes, Android has a lot of strange behavior 😁

**Comment by RichardBeisser** [comment]
> Update: My mistake about service path and package name...

what are the correct package name and service path for Versions >= 1.0.0, for App-Version ans for debug-Version?

> I also recommend to uninstall all app packages release and debug, then reboot device. Because sometimes Android still handle Accessibility service, even app was removed. Yes, Android has a lot of strange behavior 😁

I have exactly done this after you posted first, but still 
![Unbenannt](https://user-images.githubusercontent.com/47367173/211084282-95417b7f-6db5-4146-9542-0872656eedf0.png)

**Comment by bmx666** [comment]
Hi @RichardBeisser 

I checker your command on Android Emulators

> adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner.debug/com.github.bmx666.appcachecleaner.AppCacheCleanerService

And it works fine. Anyway you can remove ".debug" suffix, recompile APK, remove all packages debug/release from FireOS and install recompiled APK

remove this section from [build.gradle](https://github.com/bmx666/android-appcachecleaner/blob/main/app/build.gradle)

>        debug {
>            applicationIdSuffix '.debug'
>       }

then command should be the same like on 0.1.5

> adb shell settings put secure enabled_accessibility_services com.github.bmx666.appcachecleaner/com.github.bmx666.appcachecleaner.AppCacheCleanerService

**Comment by RichardBeisser** [comment]
hi @bmx666
now I got it working.
But I have another problem. The App doesnt write a logfile. The app asks where so save the logfile, but the file is empty.
Anything I can do?

**Comment by bmx666** [comment]
Hi @RichardBeisser 

Ok, you can try to replace logging into logcat instead of log-file

Replace on that in [Logger.kt](https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/debug/java/com/github/bmx666/appcachecleaner/log/Logger.kt)

```kotlin
        @JvmStatic private fun initializeTimber(logFile: File) {
            Timber.plant(Timber.DebugTree())
            //Timber.plant(TimberFileTree(logFile))
        }
```

Then use `adb logcat | grep com.github.bmx666.appcachecleaner | grep Logger`

**Comment by bmx666** [comment]
Hi @RichardBeisser 

Yes, because grub logs into file and saving log-file on device are separated.

But you can turn off it, just comment at file [AppCacheCleanerActivity.kt](https://github.com/bmx666/android-appcachecleaner/blob/main/app/src/main/java/com/github/bmx666/appcachecleaner/AppCacheCleanerActivity.kt) 

```kotlin
private val mLocalReceiver = object : BroadcastReceiver() {
        override fun onReceive(context: Context?, intent: Intent?) {
            when (intent?.action) {
                Constant.Intent.CleanCacheAppInfo.ACTION -> {
                    startApplicationDetailsActivity(intent.getStringExtra(Constant.Intent.CleanCacheAppInfo.NAME_PACKAGE_NAME))
                }
                Constant.Intent.CleanCacheFinish.ACTION -> {
                    cleanCacheFinish(
                        intent.getBooleanExtra(Constant.Intent.CleanCacheFinish.NAME_INTERRUPTED,
                            false))
                    //if (BuildConfig.DEBUG)
                    //    saveLogFile()
                }
            }
        }
    }
```

**Comment by bmx666** [comment]
Anyway, I can't find anything helpful in your logs, looks like FireOS has a different behavior, modified or other restrictions related to Accessibility service. Better to ask about that on Google Tracker
