### ISSUE TITLE
"Clean current app's cache" Quick Setting tile

### ISSUE THREAD

**Issue by e-t-l** [bmx666/android-appcachecleaner#61]
Thanks for all your work on this fantastic app! One helpful feature, similar but not identical to #24, would be a Quick Settings tile that targets only the app that is currently in active (aka in the foreground) and:

1. Force stops
2. Clears cache
3. Reopens app

That way if an app is misbehaving, all the user has to do is swipe down the notification shade and tap CacheCleaner's tile.

**Comment by kyoyacchi** [comment]
Hi @bmx666 There is an open source app that does this (quick tile) it opens a pop-up.
https://github.com/dead8309/Kizzy
Here it is, can you check if you can?

**Comment by bmx666** [comment]
Hi @kyoyacchi , thanks for the link, I will check it later.

**Comment by bmx666** [comment]
Hi @e-t-l  and @kyoyacchi , I made a draft of QS tile for Cache Cleaner to show dialog windows for enabling Usage stats and Accessibility service. If everything is enabled then QS tile highlights. Could you please check if it works on your side?

[app-release.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/13326676/app-release.apk.zip)

Anyway, final step should show dialog window with several options:
* clean user/system/all apps without selection
* clean apps from list
* disable Accessibility service

But I need to refactor internal logic, because everything was related on main activity.
