### ISSUE TITLE
v1.3.1 :  Xiaomi Redmi Note 7, nothing happened

### ISSUE THREAD

**Issue by AdrienDSlone** [bmx666/android-appcachecleaner#65]
Hello, I made some screenshots to explain my problem.

I am on a Xiaomi Note 7 with - Android 10 QKQ1.190910.002 and MIUI Global 12.5.3 Stable

So I start accessibility and run the app : 
![image](https://user-images.githubusercontent.com/50139099/216759141-1e9db60a-e9a6-45c2-bd6b-d6c0b18605e3.png)

Then I pick an app and run the process :
![image](https://user-images.githubusercontent.com/50139099/216759171-19e23b2e-e55f-487d-966c-bb684bafd966.png)

It opens App Info and get stucks here. No more steps :
![image](https://user-images.githubusercontent.com/50139099/216759199-37de04f6-7402-419d-acfa-0dd09be31f35.png)

So as my phone is in French I tried to find what keyword I should specify :
I wrote : "Stockage"
![image](https://user-images.githubusercontent.com/50139099/216759226-d1972d23-e9df-45ab-ab1b-50bc6203c0a3.png)
![image](https://user-images.githubusercontent.com/50139099/216759269-ca6f737a-7d10-4978-ab2b-90e9b02103e2.png)
and : "Effacer les données"
![image](https://user-images.githubusercontent.com/50139099/216759818-3ede1f60-e9ba-4646-bfa6-ab32d860e697.png)
![image](https://user-images.githubusercontent.com/50139099/216759312-2a8ddc48-9657-41ea-8429-cc788f7bc0b6.png)
But the issue is still there.

To detail a bit : when I clean the cache manually, I took these three steps :

1. I click on "Effacer les données" on the App Info screen :
![image](https://user-images.githubusercontent.com/50139099/216759383-104fd7fc-2229-417a-9692-113f1727397f.png)

2. Then an overlay popup asks what I want, and I choose : "Vider le cache" means "Clear the cache"
![image](https://user-images.githubusercontent.com/50139099/216759425-88ed437f-cdbe-479f-b704-f7484b2f129b.png)

3. Phone asks me if I am ok with that and I press ok.
![image](https://user-images.githubusercontent.com/50139099/216759495-68dc164e-268d-4dcd-a1fc-f720dde28ae0.png)

What I imagine is : since they're a more steps than "Storage" and "Clean cache", it could loop because it can't answer the optin. What do you think ?

**Comment by bmx666** [comment]
Hi @AdrienDSlone thanks a lot for that detailed feedback.

There are several extra steps need to add into app:
1. implement extra step, additional option in Settings to search popup dialog and find "OK"
2. need to analyze what type of View is used for button "OK" (imageview, button or something else)
3. add custom label for button "OK" (like for "Storage" and "Clean cache")

I'll take this task into the development phase a bit later as I'm currently focused on #24

**Comment by AdrienDSlone** [comment]
Hi @bmx666,

thanks for your answer. I will be there, to help when the time will be :)

**Comment by bmx666** [comment]
Hi @AdrienDSlone, thanks.

It will be nice, if you can extract Settings.apk from your smartphone then I can improve to search text "Storage" and "Clear cache" without extra requirements from your side.

Usually this packages is located at **/system/priv-app/Settings** or **/system_ext/priv-app/Settings** 

You can upload Settings.apk here, just rename apk to zip.

**Comment by bmx666** [comment]
Hi @AdrienDSlone , I extracted Settings.apk from Android Firmware for Redmi Note 7 from here -> https://xiaomifirmwareupdater.com/miui/lavender/stable/V12.5.3.0.QFGMIXM/

So you can ignore my previous message

**Comment by AdrienDSlone** [comment]
Hello @bmx666, You did all you can do, thank you for checking out ! 
I understand and totally agree that issue is not a priority so I marked it 'As not planned".

**Comment by program-kreativ** [comment]
I'm sorry, there was no solution to this issue?

**Comment by bmx666** [comment]
Hi @AdrienDSlone and @program-kreativ I made first test version for your case.
In Settings -> Other -> Clean cache scenario -> Xiaomi Redmi Note 7

Could you please run test on 2-3 apps and attach log here?

DEBUG APK (remove .zip extension and install APK-file) - 
[app-debug-Xiaomi-v1.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11226966/app-debug.apk.zip)

**Comment by program-kreativ** [comment]
Hello, I apologize for taking so long to answer. I received logs and recorded a video (My device is in Russian, but I can make a record in English).
I uploaded all the files to the disks:
Google Disk: https://drive.google.com/drive/folders/10ygZRzAxJVpBGRVdhULKlBxRGiLAB8SN
Yandex Disk: https://disk.yandex.ru/d/-PedJEKBL2mIwg

Let me know if there's anything else I can do to help.

**Comment by bmx666** [comment]
Hi @program-kreativ  thanks for feedback, unfortunately according your logs Cache Cleaner has no access to Settings UI View tree, maybe due to Xiaomi restriction, only logs about -> open App Info and Service was interrupted. Sorry, but I can't do anything more here, seems Xiaomi MIUI requires some extra rights to get and debug Accessibility for 3rd party apps.

**Comment by bmx666** [comment]
Hi @AdrienDSlone and @program-kreativ I got access to a paid service that provides access to physical Xiaomi smartphones with MIUI Global:

* Xiaomi 12 Pro - A12 - MIUI Global 13.0.9
* Xiaomi Redmi 8 - A10 - MIUI Global 12.5.2
* Xiaomi Redmi 9A - A10 - MIUI Global 12.0.18
* Xiaomi Redmi Note 9 - A10 - MIUI Global 12.0.8
* Xiaomi Redmi Note 9 - A11 - MIUI Global 12.5.4
* Xiaomi Redmi Note 9 Pro Max - A10 - MIUI Global 12.0.4
* Xiaomi Redmi Note 12 Pro 5G - A12 - MIUI Global 13.0.4
* Xiaomi Redmi Y2 - A9 - MIUI Global 12.0.2

I verified Cache Cleaner on all of these smartphones and I didn't found any issue related to default cleaning strategy which is using by default for all other smartphones. Meanwhile from attached video by @program-kreativ  I noticed completely different behavior of "App Info" neither that MIUI Global.

It seems that this problem can only be related to the "regional" firmware supplied by Xiaomi or Xiaomi Redmi Note 7 because I don't have the opportunity to test it, but for Xiaomi MIUI Global -> Settings -> Apps Menu displays a different UI for the user (which you have in the attached video and I don't know how to call it yet). Because in all cases, when you hold the app icon and click "App Info" menu, a completely different interface is shown, which is opened by Cache Cleaner.

I recorded and post video for Xiaomi Redmi Note 9 Pro Max - A10 - MIUI Global 12.0.4 - https://streamable.com/69p35c

**Comment by program-kreativ** [comment]
This is probably because I have the Russian version of the firmware (I attached a screenshot). 
![IMG_20230416_223646](https://user-images.githubusercontent.com/74489959/232338098-2f1e8a6c-7d0c-4c86-8157-c4821b066a8d.jpg)
I don't know why Xiaomi is doing this, because it requires significantly more developers. Thank you so much for your help. Where can I try to configure the buttons that Cash cleaner will click on myself, where is this section in the source code?

**Comment by bmx666** [comment]
Hi @program-kreativ I'm continue to investigate this, looks like it runs app -> **com.miui.securitycenter** instead of **com.android.settings**. I will try to build a new debug version soon that uses UI from **com.miui.securitycenter**, at least I have access to tree view UI and I can dump it. Let's see.

**Comment by program-kreativ** [comment]
I will be proud to conduct the necessary tests. But it's already night for me, so I could only try tomorrow. I want to note that for me this is the standard settings menu and it always looked like this for me, I attached a video example:
Google Drive: https://drive.google.com/file/d/11HPKcii2N-X04U1uGbJwGuWuwn5N6VIU/view?usp=drivesdk

**Comment by program-kreativ** [comment]
Maybe this will help. Here is information about my standard settings.
Google Drive: https://drive.google.com/file/d/11TkC4mSS86zXwTdQ9LPhyBDucDwCFzem/view?usp=drivesdk

**Comment by bmx666** [comment]
Hi @program-kreativ , thanks again, no rush, I made a new debug version I will hope it will do at least something ->  [app-debug-Xiaomi-v2.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11244729/app-debug.apk.zip)
Don't forget to select In Settings -> Other -> Clean cache scenario -> Xiaomi MIUI

I have already added Xiaomi text "Clear cache", "Clear data", "OK" for each locale, but it might not work, anyway when you have free time, please attach the generated log file here directly, without Google Drive and Yandex Drive (Github has no restriction on uploading text files in a comments).

P.S. I don't have access to your Google Drive link, it would also be best to leave this log-file for history in case something happens.

**Comment by program-kreativ** [comment]
Just in case, here is an example of clearing the cache with two variations manually:

Uploading Screenrecorder-2023-04-17-10-36-03-145.mp4…

**Comment by program-kreativ** [comment]
Here is an example of clearing the cache manually (two ways):

https://user-images.githubusercontent.com/74489959/232417290-69c9fe76-e357-4f66-bec4-4e44d649b231.mp4

**Comment by bmx666** [comment]
Hi @program-kreativ, thanks a lot for the log files.  Now I can see the full UI tree and don't worry, I already have the complete cache clear script.
  However, the problem remains with the last dialog "Clear cache?  OK, Cancel" when the accessibility service performs a "Clear Cache" click to display the last dialog, then there is no new UI change event in Android... Need to check this.

**Comment by program-kreativ** [comment]
Maybe I misunderstood something. Is that what I should check? I just don't know how.

**Comment by bmx666** [comment]
Hi @program-kreativ sorry about that, I found and fixed an issue in my code related to Cache Clean process, here a new debug version, it should work now - [app-debug-Xiaomi-v3.apk.zip](https://github.com/bmx666/android-appcachecleaner/files/11247849/app-debug.apk.zip)

**Comment by program-kreativ** [comment]
Success. I have tested, the program works successfully. Cleans all the applications as many as I have selected. And then forcibly offers to save logs.
[appcachecleaner-log(Google Maps).txt](https://github.com/bmx666/android-appcachecleaner/files/11248001/appcachecleaner-log.Google.Maps.txt)

**Comment by program-kreativ** [comment]
Cool👍👍👍

**Comment by AdrienDSlone** [comment]
Thanks you very much, I work just fine ! Awesome !
