### ISSUE TITLE
Doesn't Do Anything in Some UI

### ISSUE THREAD

**Issue by NR8124** [bmx666/android-appcachecleaner#7]
I m using Realme 7 device, and this app does not do anything during the process of cleaning in Ralme UI 2.0 running on android 11.
so i checked on my another phone of micromax in 2b which is also on android 11,
but again it does not worked properly and doesn't cleared the cached data..
can u please try to fix it ?

**Comment by bmx666** [comment]
Hi @NR8124, I watched Ralme UI 2.0 and it's using customized Settings UI, and that affect search off UI-elements and behavior.

BTW, what language are you using? I notice a lot of customized UI has different naming of elements for different languages, except English US stay the same.

I'm working on debug extension to record UI elements on screen and find correct UI-elements
see -> https://github.com/bmx666/android-appcachecleaner/issues/6#issuecomment-1146811262

**Comment by NR8124** [comment]
> BTW, what language are you using?

i am using English US

**Comment by bmx666** [comment]
> there is a similar app on playstore which works very well but it shows lots of ads and not an open source...
https://play.google.com/store/apps/details?id=com.dp.cachemaster&hl=en&gl=US

@NR8124 yes, I know a lot similar apps, first of all they have long history and a lot of clients, big teams, payable salary, access to different kind of Android smartphones. I made this app for fun as open-source for myself and for other people, without crappy ads and delays. Since I'm not sure app will be sponsored someday, so please left this comments out of scope of issue.

P.S. As I mentioned before in another issue, without physical access it hard to trace UI with Accessibility, I have only 2 Android smartphones (both have vanilla Android, 11 and 12), and Android emulators only from 6 to 13 😃

**Comment by NR8124** [comment]
Yes, i love and respect  your efforts and hard work ❤🙌 and as i mentioned i m using this app just because this is open source.
 My point was , if it is possible for you  then please try to fix that tracing UI element issue in some UIs..

**Comment by bmx666** [comment]
Hi @NR8124 can you collect logs with debug version of app ?
Select 2-3 apps and wait when app will be finished.

https://github.com/bmx666/android-appcachecleaner/issues/6#issuecomment-1172952421

**Comment by NR8124** [comment]
[appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/9034899/appcachecleaner-log.txt)


Here is the log of latest debug application u asked for...

**Comment by bmx666** [comment]
> [appcachecleaner-log.txt](https://github.com/bmx666/android-appcachecleaner/files/9034899/appcachecleaner-log.txt)
> 
> Here is the log of latest debug application u asked for... For realme ui 2.0 Android 11 ( English)

@NR8124 thanks, now I see, it seems the same issue like I got before related to custom "text" in Settings.

Google AOSP:
* Android 10 and later have original string "Storage & cache"
* Android 9 and early have original string "Storage"

Huawei, MIUI, RealMe and other:
* "Storage usage"
* "Storage use"
* "Storage used"

There is no problem to search text matching (like "storage"), but due to specific some languages have different suffix, prefix and ending.

It will be SUPER helpful if you share with me original **Settings.apk** from RealMe firmware.
You can get it by "Total commander" or similar file browser.
**Settings.apk** can be found at:
* root -> /system/app/Settings
* root -> /system/priv-app/Settings
* root -> /system/system_ext/app/Settings
* root -> /system/system_ext/priv-app/Settings
* root -> /vendor/app/Settings
* root -> /vendor/priv-app/Settings

NOTE: don't confuse with SettingsProvider (it's Android content provider for Settings)
NOTE: For example on Huawei folder can be named as **MIUISettings**

**Comment by NR8124** [comment]
I tried to access root directory but it shows that phone is not rooted so action can't be done

**Comment by bmx666** [comment]
Hi @NR8124 can you try release [v0.0.6](https://github.com/bmx666/android-appcachecleaner/releases/tag/v0.0.6) ?
I added button "add extra search text" that can help to solve thousands variations of custom UI.
[See more in README](https://github.com/bmx666/android-appcachecleaner/blob/main/README.md#customized-settings-ui)

**Comment by NR8124** [comment]
Cool !! Its working properly Now... 😍 I really appreciate your efforts and that idea of user input text.... 🙌

But there is only one  problem its bit slow... See if it can be fixed in next release...

**Comment by bmx666** [comment]
Yes, I noticed on low performance smartphones app is slow, I will try to optimize it, but I will close this issue. Thanks a lot for feedback.
