### ISSUE TITLE
Cache Cleaner Hanging

### ISSUE THREAD

**Issue by terrystech** [bmx666/android-appcachecleaner#74]
The app seems to be working great and then it will hang.  If it does come out of the hang out says it was interrupted.  Here is where it hung this morning.
![Screenshot_20230208-082727](https://user-images.githubusercontent.com/69647004/217544362-9aac970d-67c2-40fe-b129-c1094c4f9d69.png)

**Comment by bmx666** [comment]
Hi @terrystech , please read issue #8 . I can't fix this because it's related to Android System. Cache Cleaner just wait feedback from Accessibility service, but it doesn't happen. I set timeout for 35 seconds, because on old devices it can take 30 seconds to calculate cache and notify service back.
