### ISSUE TITLE
Clean cache was interrupted

### ISSUE THREAD

**Issue by gbdomubpkm** [bmx666/android-appcachecleaner#77]
With the last two updates, the app sometimes freeze on a app and i get the message  'Clean cache was interrupted'.
Impossible to understand why but you may have noticed this. This can happen on any list and not always the same app. I had never had this problem before.

**Comment by bmx666** [comment]
Hi @gbdomubpkm , please read issue https://github.com/bmx666/android-appcachecleaner/issues/8 . I can't fix this because it's related to Android System. Cache Cleaner just wait feedback from Accessibility service, but it doesn't happen. I set timeout for 35 seconds, because on old devices it can take 30 seconds to calculate cache and notify service back.

**Comment by gbdomubpkm** [comment]
All right. Thank you.  I had never faced this problem before.
