### ISSUE TITLE
Apps deselected on start in base lists

### ISSUE THREAD

**Issue by gbdomubpkm** [bmx666/android-appcachecleaner#78]
V 1.4.2
The 3 base lists now have all apps deselected at the start of each use. Is it wanted ?

**Comment by bmx666** [comment]
Yes, because the base list has no persistent state, and the cache size of each application after cleaning is different.  Custom lists have now been implemented, please check Settings. You can create a list of required applications for your purposes and clear it. This was done for the next step -> #30
Also filter by size will be implemented soon -> #71
