### ISSUE TITLE
Custom Apps Bug?

### ISSUE THREAD

**Issue by maverick74** [bmx666/android-appcachecleaner#87]
Hi,

I'm trying to use the custom apps list 

However, after i get a popup asking for each app on the list in which i have to - manually - clear the cache, i always get this screen

![Screenshot_com github bmx666 appcachecleaner](https://user-images.githubusercontent.com/14912461/220667747-0e7e8b38-e67f-43c2-a95e-96fd99afeb4a.jpg)

Is it a bug?

I was under the impression that the app:
1. would - automatically - clear all the apps cache (instead of just bringing the android app options for me to manually clean it)
2. present a result on how much was cleaned (instead of 0 bytes)

**Comment by bmx666** [comment]
Hi @maverick74, no it's not a bug. Algorithm is pretty simple - get cache size of selected apps before clean and after, then sum values of subtraction (old - new).

There are several reasons could be why 0 is displayed:
1. Clean cache process is postponed by system. I will do it later... So **Cache Cleaner** get back the same size of cache.
2. Sometimes **Cache Cleaner** can't get cache size after the cleaning process - something related to Android system issue, it return "null" instead of usage info, and I decided to return 0 in that case.
3. Some background services of apps automatically restore cache back, so when you press "Clean Cache" button and see 0 bytes, then it will reset back to some cache size back after.
4. Some background services during cleaning process can allocate even more cache, in that case I decided return also 0.
5. There are 2 types of cache (internal and external) -> read my comment and internal comment 6 in the issue #25

**Comment by bmx666** [comment]
Hi @maverick74 again, sorry, you was right, it's a bug and text is not be displayed, because cache size is never calculated for custom list to save time.

**Comment by bmx666** [comment]
Hi @maverick74 , fix was done in version 1.5.4 👍

**Comment by maverick74** [comment]
Hi @bmx666 

OK, but still... shouldn't it clear the cache without prompting me - for each app on the list - to push the button manually to clear the apps' cache?

For example, **google speech services** app uses a LOT of space... but it keeps showing me the options menu page i use to go manually to clear the cache (and i have to do it manually)... that happens in other apps as well.

I thought that when the clear user apps cache's button was pressed (and the list selected) it would clean all the cache's alone without requiring me any actions

**Comment by bmx666** [comment]
Hi @maverick74 ,

Cache Cleaner has primitive algorithm:
1. Open AppInfo
2. Find "Storage" menu and press it
3. Find "Clear cache" button and press it

There are a lot of restrictions made by Google, before in Android 6 developers had the freedom to do anything and collect information about various scenarios, but due to a lot of scammers, Google disallows everything and Accessibility only returns the Node View (ID + text), and you can only perform clicks. That's all! Very limited functionality.

Can you provide screenshots, smartphone model, Android version? Because on emulators and my smartphone I have no this option, open default, like other apps.

**Comment by bmx666** [comment]
Can you create a new issue for that? Because it's not related to that issue.

**Comment by maverick74** [comment]
> Can you create a new issue for that? Because it's not related to that issue.

Sorry for taking so long...
so, after reading some of your issues i found that #65 and #92 are mostly my problem
(i'm on xiaomi redmi with MIUI 11... so i guess i'll subscribe those issues and follow them)
