### ISSUE TITLE
App doesnt wait while Android is calculating storage-usage

### ISSUE THREAD

**Issue by RichardBeisser** [bmx666/android-appcachecleaner#94]
Hello,

i am using the app on an older Andrid 7.0 Device.
Because the device is older and slower, when you push button "storage", android is showing the message "calculating" before showing storage usage and before buttons for clean cache gets enabled.

Of course, the waiting time for this is below 30 seconds.

So it seems that the app doesnt recognise this dialog and doesnt wait

Anything you can do here?

**Comment by bmx666** [comment]
Hi @RichardBeisser , yes I thought about create custom timeout in Settings, because I hardcoded 30 seconds when I tested one of my old Huawei Y7, it also has problem with cache calculation due to EMMC degradation.
I'm thinking to add custom timeout in app Settings soon, and users can increase it for old phones. Because for modern UFS and powerful CPU it can took only 3-5 seconds in worse cases.
